# Copyright (c) 2023-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("../../../os_account.gni")
import("../../../services/accountmgr/os_account_service.gni")
import("//build/config/features.gni")
import("//build/test.gni")

config("osaccount_stub_common_config") {
  include_dirs = [
    "${services_path}/accountmgr/include/bundle_manager_adapter",
    "${services_path}/accountmgr/include",
    "${services_path}/accountmgr/include/osaccount",
    "${os_account_innerkits_native_path}/include",
    "${os_account_path}/test/fuzztest/osaccount_stub/common",
  ]
  cflags = [
    "-g",
    "-O0",
    "-Wno-unused-variable",
    "-fno-omit-frame-pointer",
  ]
  if (use_libfuzzer) {
    cflags += [ "-DFUZZ_TEST" ]
  }
  if (target_cpu == "arm") {
    cflags += [ "-DBINDER_IPC_32BIT" ]
  }
  defines = [
    "ACCOUNT_LOG_TAG = \"OsAccountFuzzTest\"",
    "LOG_DOMAIN = 0xD001B00",
  ]
}

config("osaccount_stub_create_update_config") {
  include_dirs = [
    "${os_account_path}/test/fuzztest/osaccount_stub/common",
    "${app_account_services_path}/test/mock/common",
    "${services_path}/accountmgr/test/mock/common",
    "${services_path}/accountmgr/test/mock/os_account",
    "${services_path}/accountmgr/include",
    "${services_path}/accountmgr/include/osaccount",
    "${services_path}/accountmgr/include/domain_account",
    "${services_path}/accountmgr/include/distributed_account",
    "${services_path}/accountmgr/include/os_account_subprofile",
    "${services_path}/accountmgr/include/common/database/kvstore",
    "${services_path}/accountmgr/include/common/database",
    "${services_path}/accountmgr/test/mock/include",
    "${app_account_innerkits_native_path}/include",
    "${os_account_path}/frameworks/osaccount/core/include",
    "${os_account_dfx_path}/data_dfx",
    "${common_path}/log/include",
    "${common_path}/perf_stat/include",
    "${innerkits_common}/include",
    "${innerkits_path}/include",
  ]
  cflags_cc = [ "-DACCOUNT_TEST" ]
  if (has_user_idm_part) {
    cflags_cc += [ "-DHAS_USER_IDM_PART" ]
  }
  if (use_libfuzzer) {
    cflags_cc += [ "-DFUZZ_TEST" ]
  }
  if (os_account_distributed_feature && !use_libfuzzer) {
    cflags_cc += [ "-DENABLE_FILE_WATCHER" ]
    if (has_huks_part) {
      cflags_cc += [ "-DHAS_HUKS_PART" ]
    }
  }
  if (os_account_support_lock_os_account) {
    cflags_cc += [ "-DSUPPORT_LOCK_OS_ACCOUNT" ]
  }
  if (os_account_support_domain_accounts) {
    cflags_cc += [ "-DSUPPORT_DOMAIN_ACCOUNTS" ]
  }
  if (target_cpu == "arm64") {
    defines = [ "_ARM64_" ]
  }
}

group("fuzztest") {
  testonly = true

  deps = [
    "activateosaccountstub_fuzzer:ActivateOsAccountStubFuzzTest",
    "checkosaccountconstraintenabledstub_fuzzer:CheckOsAccountConstraintEnabledStubFuzzTest",
    "createosaccountwithfullinfoinosaccountinfo_fuzzer:CreateOsAccountWithFullInfoInOsAccountInfoFuzzTest",
    "createosaccountwithfullinfostub_fuzzer:CreateOsAccountWithFullInfoStubFuzzTest",
    "createosaccountwithshortnamestub_fuzzer:CreateOsAccountWithShortNameStubFuzzTest",
    "deactivateosaccountstub_fuzzer:DeactivateOsAccountStubFuzzTest",
    "dumpstatestub_fuzzer:DumpStateStubFuzzTest",
    "getforegroundosaccountdisplayidstub_fuzzer:GetForegroundOsAccountDisplayIdStubFuzzTest",
    "getforegroundosaccountlocalidstub_fuzzer:GetForegroundOsAccountLocalIdStubFuzzTest",
    "getosaccountallconstraintsstub_fuzzer:GetOsAccountAllConstraintsStubFuzzTest",
    "getosaccountlocalidbyserialnumberstub_fuzzer:GetOsAccountLocalIdBySerialNumberStubFuzzTest",
    "getosaccountnamebyidstub_fuzzer:GetOsAccountNameByIdStubFuzzTest",
    "getosaccountprofilephotostub_fuzzer:GetOsAccountProfilePhotoStubFuzzTest",
    "getosaccountshortnamebyidstub_fuzzer:GetOsAccountShortNameByIdStubFuzzTest",
    "getosaccounttypestub_fuzzer:GetOsAccountTypeStubFuzzTest",
    "getserialnumberbyosaccountlocalidstub_fuzzer:GetSerialNumberByOsAccountLocalIdStubFuzzTest",
    "isosaccountactivedstub_fuzzer:IsOsAccountActivedStubFuzzTest",
    "isosaccountcompletedstub_fuzzer:IsOsAccountCompletedStubFuzzTest",
    "isosaccountconstraintenablestub_fuzzer:IsOsAccountConstraintEnableStubFuzzTest",
    "isosaccountdeactivatingstub_fuzzer:IsOsAccountDeactivatingStubFuzzTest",
    "isosaccountexistsstub_fuzzer:IsOsAccountExistsStubFuzzTest",
    "isosaccountforegroundstub_fuzzer:IsOsAccountForegroundStubFuzzTest",
    "isosaccountverifiedstub_fuzzer:IsOsAccountVerifiedStubFuzzTest",
    "osaccountstatereplycallbackstub_fuzzer:OsAccountStateReplyCallbackStubFuzzTest",
    "proccreateosaccountstub_fuzzer:ProcCreateOsAccountStubFuzzTest",
    "proccreateosaccountwithfullinfostub_fuzzer:ProcCreateOsAccountWithFullInfoStubFuzzTest",
    "proccreateosaccountwithoutoptionsstub_fuzzer:ProcCreateOsAccountWithoutOptionsStubFuzzTest",
    "proccreateosaccountwithshortnamestub_fuzzer:ProcCreateOsAccountWithShortNameStubFuzzTest",
    "procsetosaccountnamestub_fuzzer:ProcSetOsAccountNameStubFuzzTest",
    "procstartosaccountstub_fuzzer:ProcStartOsAccountStubFuzzTest",
    "queryosaccountbyidstub_fuzzer:QueryOsAccountByIdStubFuzzTest",
    "queryosaccountconstraintsourcetypesstub_fuzzer:QueryOsAccountConstraintSourceTypesStubFuzzTest",
    "removeosaccountstub_fuzzer:RemoveOsAccountStubFuzzTest",
    "setcurrentosaccountisverifiedstub_fuzzer:SetCurrentOsAccountIsVerifiedStubFuzzTest",
    "setdefaultactivatedosaccountstub_fuzzer:SetDefaultActivatedOsAccountStubFuzzTest",
    "setglobalosaccountconstraintsstub_fuzzer:SetGlobalOsAccountConstraintsStubFuzzTest",
    "setosaccountconstraintsstub_fuzzer:SetOsAccountConstraintsStubFuzzTest",
    "setosaccountisverifiedstub_fuzzer:SetOsAccountIsVerifiedStubFuzzTest",
    "setosaccountprofilephotostub_fuzzer:SetOsAccountProfilePhotoStubFuzzTest",
    "setosaccounttoberemovedstub_fuzzer:SetOsAccountToBeRemovedStubFuzzTest",
    "setspecificosaccountconstraintsstub_fuzzer:SetSpecificOsAccountConstraintsStubFuzzTest",
    "subscribeosaccountconstraintstub_fuzzer:SubscribeOsAccountConstraintStubFuzzTest",
    "subscribeosaccountstub_fuzzer:SubscribeOsAccountStubFuzzTest",
    "unsubscribeosaccountconstraintstub_fuzzer:UnsubscribeOsAccountConstraintStubFuzzTest",
    "unsubscribeosaccountstub_fuzzer:UnsubscribeOsAccountStubFuzzTest",
    "updateosaccountwithfullinfostub_fuzzer:UpdateOsAccountWithFullInfoStubFuzzTest",
    "procgetcreatedosaccountnumfromdatabasestub_fuzzer:procgetcreatedosaccountnumfromdatabaseStubFuzzTest",
    "procgetserialnumberfromdatabasestub_fuzzer:procgetserialnumberfromdatabasestubFuzzTest",
    "procgetmaxallowcreateidfromdatabasestub_fuzzer:procgetmaxallowcreateidfromdatabasestubFuzzTest",
    "procgetosaccountfromdatabasestub_fuzzer:procgetosaccountfromdatabaseStubFuzzTest",
    "procgetosaccountlistfromdatabasestub_fuzzer:procgetosaccountlistfromdatabasestubFuzzTest",
  ]

  if (os_account_support_domain_accounts) {
    deps += [
      "binddomainaccountstub_fuzzer:BindDomainAccountStubFuzzTest",
      "createosaccountfordomainstub_fuzzer:CreateOsAccountForDomainStubFuzzTest",
      "createosaccountfordomainwithoutoptionsstub_fuzzer:CreateOsAccountForDomainWithoutOptionsStubFuzzTest",
      "getosaccountdomaininfostub_fuzzer:GetOsAccountDomainInfoStubFuzzTest",
      "getosaccountlocalidfromdomainstub_fuzzer:GetOsAccountLocalIdFromDomainStubFuzzTest",
    ]
  }

  if (os_account_support_lock_os_account) {
    deps += [
      "lockosaccountstub_fuzzer:LockOsAccountStubFuzzTest",
      "publishosaccountlockeventstub_fuzzer:PublishOsAccountLockEventStubFuzzTest",
    ]
  }
}
