# Copyright (c) 2023-2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("../osaccount_stub_shared.gni")

ohos_fuzztest("CreateOsAccountWithFullInfoInOsAccountInfoFuzzTest") {
  module_out_path = fuzz_output_path
  fuzz_config_file = "."
  configs = [
    "${app_account_services_path}/test/mock:mock_accountmgr_config",
    "${app_account_services_path}/test/mock:accountmgr_config",
    "${os_account_path}/test/fuzztest/osaccount_stub:osaccount_stub_common_config",
    "${os_account_path}/test/fuzztest/osaccount_stub:osaccount_stub_create_update_config",
  ]
  sources = [ "createosaccountwithfullinfoinosaccountinfo_fuzzer.cpp" ]
  sources += osaccount_stub_create_update_sources
  version_script = "${services_path}/accountmgr/libaccountmgr.map"
  deps = osaccount_stub_deps
  deps += osaccount_stub_create_update_deps
  external_deps = osaccount_stub_ext_deps
  external_deps += osaccount_stub_create_update_ext_deps
}
